apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  labels:
    app: northwind
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 8Gi
  storageClassName: gp2
