FROM mysql:5.7
RUN apt-get update && apt-get install -y iputils-ping

#setpassewd
ENV MYSQL_ROOT_PASSWORD=changeit

ADD 0-northwind-default-current-timestamp.sql /docker-entrypoint-initdb.d
ADD 1-northwind-data.sql /docker-entrypoint-initdb.d

#add healthcheck
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD  mysqladmin ping -uroot -pchangeit || exit 1

VOLUME /var/lib/mysql


