FROM node:latest
ENV APP_ROOT=/app APP_PORT="3000"
#create APP dir and cd
WORKDIR ${APP_ROOT}
#copy files and directory
ADD main.js .
ADD package.json .
ADD package-lock.json .
ADD public public
ADD views views
#run dependencies
RUN npm install

# tell what port we are using
EXPOSE ${APP_PORT}

ENTRYPOINT [ "node", "main.js" ]

#CMD [ "${APP_PORT}" ]

#add healthcheck
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -s -f http://localhost:${APP_PORT}/health || exit 1
